name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
        
        
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
      
      
 jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: deploy
      
      
      jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
