name: Deployment

on:
push:
branches:
- main

jobs:
deployment:
runs-on: ubuntu-latest
environment: Dev
steps:
- name: deploy


jobs:
deployment:
runs-on: ubuntu-latest
environment: QA
steps:
- name: deploy


jobs:
deployment:
runs-on: ubuntu-latest
environment: Prod
steps:
- name: deploy
